// Getters and setters are generated by default
// You can add code to a getter or setter

class GetterSetter {

    var name: String = ""
        get() = field.uppercase()
        set(value) {
            field = value.trim()
        }
}

fun main() {
    val getterSetter = GetterSetter()
    getterSetter.name = "Kylo Ren "
    println("[${getterSetter.name}]")
}
